Bug fix, and add feature for jail-shell-setup

diff --git a/bin/jail-shell-setup b/bin/jail-shell-setup
--- a/bin/jail-shell-setup
+++ b/bin/jail-shell-setup
@@ -3,6 +3,7 @@
 # Copyright (C) 2017 Ruilin Peng (Nick) <pymumu@gmail.com>
 #
 
+JAIL_DIR=
 JAIL_ROOT_DIR=
 CONF_PATH=/etc/jail-shell/jail-config
 JAIL_SHELL_HOME=/usr/local/jail-shell
@@ -14,9 +15,18 @@ JAIL_SHELL_CONF=/etc/jail-shell/jail-shell.conf
 
 get_root_dir()
 {
-	JAIL_ROOT_DIR="`grep "^ *JAIL_HOME" $JAIL_SHELL_CONF | awk '{print $2}'`"
+	JAIL_DIR="`grep "^ *JAIL_HOME" $JAIL_SHELL_CONF | awk '{print $2}'`"
 	
-	if [ -z "$JAIL_ROOT_DIR" ]; then
+	if [ -z "$JAIL_DIR" ]; then
+		return 1
+	fi
+
+	JAIL_DIR="`readlink -e $JAIL_DIR`"
+	if [ ! -d "$JAIL_DIR" ]; then
+		return 1
+	fi
+
+	if [ "$JAIL_DIR" = "/" ]; then
 		return 1
 	fi
 
@@ -27,25 +37,46 @@ showhelp()
 {
 	echo "Usage: jail-shell-setup [OPTION]"
 	echo "Options:"
-	echo "  --list        list jail names."
-	echo "  --setup       setup jail-shell."
-	echo "-h, --help      show this help message."
+	echo "  --list                    list jail names."
+	echo "  --install [name | all]    install jail-shell from config file."
+	echo "  --remove [name]           remove a jial-shell."
+	echo "  --clean [name]            cleanup a jial-shell."
+	echo "  -h, --help                show this help message."
 }
 
 link_cp()
 {
 	local src=$1
 	local target=$2
+	local link=$3 # 1 for link and copy, 0 for copy only
+
+	if [ -z "$link" ]; then
+		link=1
+	fi
+
 	if [ -d "$target" ]; then
 		target="$target/`basename $src`"
 	fi
 
-	ln -f $src $target 2>/dev/null
-	if [ $? -eq 0 ]; then
-		return 0
+	target_dir="`dirname $target | sed 's#/\{2,\}#/#g'`"
+	if [ ! -d "$target_dir" ]; then
+		echo "Directory $target_dir doesn't exist"
+		return 1
 	fi
 
-	cp -a $1 $2
+	link_target_dir="`readlink -e $target_dir`"
+	if [ "$target_dir" != "$link_target_dir" ]; then
+		target="$JAIL_ROOT_DIR/$link_target_dir/`basename $target`"
+	fi
+
+	if [ $link -eq 1 ]; then
+		ln -f $src $target 2>/dev/null
+		if [ $? -eq 0 ]; then
+			return 0
+		fi
+	fi
+
+	cp -a $src $target
 }
 
 cp_lib()
@@ -65,17 +96,17 @@ cp_lib()
 		DIR="`dirname $FILE`"
 		LIB_FILE="$FILE"
 		if [ -h "$FILE" ]; then
-			if [ ! -d "$1/$DIR" ]; then
-				mkdir -m 0755 -p $1/$DIR
+			if [ ! -d "$JAIL_ROOT_DIR/$DIR" ]; then
+				mkdir -m 0755 -p $JAIL_ROOT_DIR/$DIR
 			fi
-			link_cp $FILE $1/$DIR/
+			link_cp $FILE $JAIL_ROOT_DIR/$DIR
 			LIB_FILE="`readlink -e $FILE`"
 		fi
 		DIR="`dirname $LIB_FILE`"
-		if [ ! -d "$1/$DIR" ]; then
-			mkdir -m 0755 -p $1/$DIR
+		if [ ! -d "$JAIL_ROOT_DIR/$DIR" ]; then
+			mkdir -m 0755 -p $JAIL_ROOT_DIR/$DIR
 		fi
-		link_cp $LIB_FILE $1/$DIR/
+		link_cp $LIB_FILE $JAIL_ROOT_DIR/$DIR
 	done < $LIBS_ALL_FILE
 
 	rm -f $LIBS_ALL_FILE
@@ -89,96 +120,120 @@ add_elf_file()
 
 dir()
 {
-	local userinfo="$4"
-	if [ $# -ne 4 ]; then
+	local userinfo="$3"
+	if [ $# -ne 3 ]; then
+		echo "arg number is invalid"
 		return 1
 	fi
 	user=${userinfo##*:}
 	group=${userinfo#*:}
-	install -o $user -g $group -m $3 -d $1/$2  
+	install -o $user -g $group -m $2 -d $JAIL_ROOT_DIR/$1  
 }
 
 file()
 {
-	local userinfo="$5"
-	if [ $# -ne 5 ]; then
-		return 1
-	fi
-	user=${userinfo##*:}
-	group=${userinfo#*:}
-	cp -a $2 $1/$3
-	if [ $? -ne 0 ]; then
+	local userinfo="$4"
+	if [ $# -ne 4 ]; then
+		echo "arg number is invalid"
 		return 1
 	fi
 
-	add_elf_file "$1/$3"
+	if [ -h "$1" ]; then
+		echo "source file is symbolic link"
+		return 1
+	fi
+
+	user=${userinfo##*:}
+	group=${userinfo#*:}
+	link_cp $1 $JAIL_ROOT_DIR/$2 0
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+	chmod $3 $JAIL_ROOT_DIR/$2
+	chown $user:$group $JAIL_ROOT_DIR/$2
+
+	add_elf_file "$JAIL_ROOT_DIR/$2"
 }
 
 clink() 
 {
-	if [ $# -ne 3 ]; then
+	if [ $# -ne 2 ]; then
+		echo "arg number is invalid"
 		return 1
 	fi
 
-	if [ -h "$2" ]; then
-		LINKED_FILE="`readlink -e $2`"
-		cp -a $2 $1/$2
+	if [ -h "$1" ]; then
+		LINKED_FILE="`readlink -e $1`"
+		ln -f -s $LINKED_FILE $JAIL_ROOT_DIR/$1
 		if [ $? -ne 0 ]; then
 			return 1
 		fi
-		clink $1 $LINKED_FILE $LINKED_FILE
+		clink $LINKED_FILE $LINKED_FILE
 		return $?
 	fi
 
-	link_cp $2 $1/$3
+	link_cp $1 $JAIL_ROOT_DIR/$2
 	if [ $? -ne 0 ]; then
 		return 1
 	fi
 
-	add_elf_file "$1/$3"
+	add_elf_file "$JAIL_ROOT_DIR/$2"
 }
 
 hlink()
 {
-	if [ $# -ne 3 ]; then
+	if [ $# -ne 2 ]; then
+		echo "arg number is invalid"
 		return 1
 	fi
 
-	ln -f $2 $1/$3
+	ln -f $1 $JAIL_ROOT_DIR/$2
 	if [ $? -ne 0 ]; then
 		return 1
 	fi
 
-	add_elf_file "$1/$3"
+	add_elf_file "$JAIL_ROOT_DIR/$2"
 }
 
 slink()
 {
-	if [ $# -ne 3 ]; then
+	if [ $# -ne 2 ]; then
 		return 1
 	fi
 
-	ln -f -s $2 $1/$3
+	ln -f -s $1 $JAIL_ROOT_DIR/$2
 }
 
 cmd()
 {
-	local userinfo="$5"
-	if [ $# -lt 5 ]; then
+	local userinfo="$4"
+	if [ $# -lt 4 ]; then
+		echo "arg number is invalid"
 		return 1
 	fi
 	user=${userinfo##*:}
 	group=${userinfo#*:}
 
-	ln -f -s $JAIL_CMD $1$2
+	ln -f -s $JAIL_CMD $JAIL_ROOT_DIR/$1
 	if [ $? -ne 0 ]; then
 		return 1
 	fi
 
-	LINK_NAME="`basename $2`"
-	ln -f -s $3 $JAIL_COMMAND_PATH/$LINK_NAME
+	LINK_NAME="`basename $1`"
+	ln -f -s $2 $JAIL_COMMAND_PATH/$LINK_NAME
 	if [ $? -ne 0 ]; then
 		return 1
+	fi
+}
+
+add_basic_files()
+{
+	if [ ! -f "$JAIL_ROOT_DIR/etc/passwd" ]; then
+		echo "root:x:0:0:root:/root:/bin/bash" > $JAIL_ROOT_DIR/etc/passwd
+	fi
+
+	if [ ! -f "$JAIL_ROOT_DIR/etc/group" ]; then
+		echo "root:x:0:" > $JAIL_ROOT_DIR/etc/group
 	fi
 }
 
@@ -198,6 +253,7 @@ setup_jail()
 
 	JAIL_COMMAND_PATH=$COMMAND_PATH/$jail_name
 	mkdir $JAIL_COMMAND_PATH 2>/dev/null
+	JAIL_ROOT_DIR="$JAIL_DIR/$jail_name"
 
 	LINE_NO=0
 	while read CMD ARGS;
@@ -218,7 +274,7 @@ setup_jail()
 			;;
 		esac
 
-		$CMD $JAIL_ROOT_DIR/$jail_name $ARGS
+		$CMD $ARGS
 		if [ $? -ne 0 ]; then
 			echo "command failed at line $LINE_NO: $CMD $ARGS"
 			return 1
@@ -226,27 +282,145 @@ setup_jail()
 	done < $jail_cfg
 
 	if [ $cp_cmd -eq 1 ]; then
-		clink $JAIL_ROOT_DIR/$jail_name $JAIL_SHELL_HOME/jail-cmd/jail-cmd $JAIL_CMD 
+		clink $JAIL_SHELL_HOME/jail-cmd/jail-cmd $JAIL_CMD 
 		if [ $? -ne 0 ]; then
 			echo "copy jail-cmd failed."
 			return 1
 		fi
 	fi
 
-	cp_lib $JAIL_ROOT_DIR/$jail_name
+	cp_lib 
 	if [ $? -ne 0 ]; then
 		echo "copy lib failed."
 		return 1
 	fi
+
+	add_basic_files
+	if [ $? -ne 0 ]; then
+		echo "add basic files failed."
+		return 1
+	fi
 }
 
-setup_jails()
+clean_jail() 
 {
-	for JAIL_CFG in `ls $CONF_PATH/*.cfg 2>/dev/null`
-	do
-		JAIL_NAME="`basename $JAIL_CFG .cfg`"
-		setup_jail "$JAIL_NAME" "$JAIL_CFG"
-	done
+	JAIL_NAME="$1"
+
+	JAIL_PATH="$JAIL_DIR/$JAIL_NAME"
+
+	JAIL_CFG="$CONF_PATH/${JAIL_NAME}.cfg"
+	if [ ! -e $JAIL_CFG ]; then
+		echo "jail $JAIL_NAME doesn't exist."
+		return 1
+	fi
+
+	if [ ! -d "$JAIL_PATH" ]; then
+		echo "jail $JAIL_NAME is not installed"
+		return 1
+	fi
+
+	cat /proc/mounts | grep "/$JAIL_NAME/" | tac | awk '{print $2}' | xargs -i umount {} 
+	if [ $? -ne 0 ]; then
+		echo "umount directories failed."
+		return 1
+	fi
+
+	fuser -k $JAIL_PATH
+	return 0
+}
+
+clean_jails()
+{
+	local ret=0
+	JAIL_NAME="$1"
+	if [ "$JAIL_NAME" = "all" ]; then
+		for JAIL_CFG in `ls $CONF_PATH/*.cfg 2>/dev/null`
+		do
+			JAIL_NAME="`basename $JAIL_CFG .cfg`"
+			JAIL_PATH="$JAIL_DIR/$JAIL_NAME"
+			if [ ! -d "$JAIL_PATH" ]; then
+				continue
+			fi
+			clean_jail "$JAIL_NAME" "$JAIL_CFG"
+			if [ $? -ne 0 ]; then
+				echo "setup jail $JAIL_NAME failed."
+				ret=1
+			fi
+		done
+
+		return $ret
+	fi
+
+	JAIL_CFG="$CONF_PATH/${JAIL_NAME}.cfg"
+	if [ ! -e $JAIL_CFG ]; then
+		echo "jail $JAIL_NAME doesn't exist."
+		return 1
+	fi
+	
+	clean_jail "$JAIL_NAME" "$JAIL_CFG"
+	if [ $? -ne 0 ]; then
+		echo "setup jail $JAIL_NAME failed."
+		ret=1
+	fi
+
+	return $ret
+}
+
+remove_jail()
+{
+	local ret=0
+	JAIL_NAME="$1"
+	
+	JAIL_CFG="$CONF_PATH/${JAIL_NAME}.cfg"
+	if [ ! -e $JAIL_CFG ]; then
+		echo "jail $JAIL_NAME doesn't exist."
+		return 1
+	fi
+
+	JAIL_PATH="$JAIL_DIR/$JAIL_NAME"
+	if [ ! -d "$JAIL_PATH" ]; then
+		echo "jail $JAIL_NAME is not installed."
+		return 1
+	fi
+
+	clean_jail $JAIL_NAME
+
+	rm -fr $JAIL_PATH
+
+	return $?
+}
+
+install_jails()
+{
+	local ret=0
+	JAIL_NAME="$1"
+	if [ "$JAIL_NAME" = "all" ]; then
+		for JAIL_CFG in `ls $CONF_PATH/*.cfg 2>/dev/null`
+		do
+			JAIL_NAME="`basename $JAIL_CFG .cfg`"
+			setup_jail "$JAIL_NAME" "$JAIL_CFG"
+			if [ $? -ne 0 ]; then
+				echo "setup jail $JAIL_NAME failed."
+				ret=1
+			fi
+		done
+
+		return $ret
+	fi
+
+	JAIL_CFG="$CONF_PATH/${JAIL_NAME}.cfg"
+	if [ ! -e $JAIL_CFG ]; then
+		echo "jail $JAIL_NAME doesn't exist."
+		return 1
+	fi
+	
+	setup_jail "$JAIL_NAME" "$JAIL_CFG"
+	if [ $? -ne 0 ]; then
+		echo "setup jail $JAIL_NAME failed."
+		ret=1
+	fi
+
+	return $ret
 }
 
 list_jail() 
@@ -254,13 +428,18 @@ list_jail()
 	for JAIL_CFG in `ls $CONF_PATH/*.cfg 2>/dev/null`
 	do
 		JAIL_NAME="`basename $JAIL_CFG .cfg`"
-		echo "$JAIL_NAME"
+		echo -n "$JAIL_NAME"
+		if [ -d "$JAIL_DIR/$JAIL_NAME" ]; then
+			echo  "\t\t Installed"
+		else
+			echo  "\t\t Not Install"
+		fi
 	done	
 }
 
 main()
 {
-	OPTS=`getopt -o h --long help,setup,list \
+	OPTS=`getopt -o h --long help,install:,remove:,clean:,list \
 		-n  "" -- "$@"`
 
 	if [ $# -eq 0 ]; then
@@ -285,8 +464,16 @@ main()
 			showhelp
 			return $!
 			shift ;;
-		--setup )
-			setup_jails
+		--install )
+			install_jails $2
+			return $?
+			shift ;;
+		--remove )
+			remove_jail $2
+			return $?
+			shift ;;
+		--clean )
+			clean_jails $2
 			return $?
 			shift ;;
 		--list )
diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,7 +17,7 @@ showhelp()
 
 start_service()
 {
-	if [ -z "`which systemctl`" ]; then
+	if [ $ISSYSTEMD -ne 0 ]; then
 		chkconfig jail-shell on
 		service jail-shell start
 		return $?
@@ -30,7 +30,7 @@ start_service()
 
 stop_service()
 {
-	if [ -z "`which systemctl`" ]; then
+	if [ $ISSYSTEMD -ne 0 ]; then
 		service jail-shell stop
 		chkconfig jail-shell off
 		return 0
@@ -44,6 +44,9 @@ stop_service()
 
 clean_service()
 {
+	if [ $ISSYSTEMD -ne 0 ]; then
+		return 0
+	fi
 	systemctl daemon-reload
 }
 
@@ -96,9 +99,11 @@ install_files()
 		return 1
 	fi
 
-	install -v -m 0644 -t $PREFIX/lib/systemd/system lib/systemd/system/jail-shell.service 
-	if [ $? -ne 0 ]; then
-		return 1
+	if [ $ISSYSTEMD -eq 0 ]; then
+		install -v -m 0644 -t $PREFIX/lib/systemd/system lib/systemd/system/jail-shell.service 
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
 	fi
 
 	install -v -m 0644 -t $PREFIX/etc/default etc/default/jail-shell 
@@ -126,13 +131,29 @@ install_files()
 
 remove_pam_config()
 {
-	sed -i '/pam_jail_shell.so/d' $PREFIX/etc/pam.d/common-session
+	sed -i '/pam_jail_shell.so/d' $PREFIX/etc/pam.d/common-session 2>/dev/null 
+	sed -i '/pam_jail_shell.so/d' $PREFIX/etc/pam.d/login 2>/dev/null
+	sed -i '/pam_jail_shell.so/d' $PREFIX/etc/pam.d/sshd 2>/dev/null
 }
 
 add_pam_config() 
 {
 	remove_pam_config
-	echo "session required		pam_jail_shell.so" >> $PREFIX/etc/pam.d/common-session
+	echo "session required		pam_jail_shell.so" >> $PREFIX/etc/pam.d/common-session 2>/dev/null
+	if [ $? -eq 0 ]; then
+		return 0
+	fi
+
+	echo "session required		pam_jail_shell.so" >> $PREFIX/etc/pam.d/login 2>/dev/null
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+
+	echo "session required		pam_jail_shell.so" >> $PREFIX/etc/pam.d/sshd 2>/dev/null
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+
 	return $?
 }
 
@@ -186,6 +207,8 @@ init_dir()
 	JAIL_SHELL_INIT_DIR=$PREFIX/etc/init.d
 	LIB_DIR=$PREFIX"`ldd /bin/sh | grep libc | awk '{print $3}' | xargs dirname`"
 	SECURITY_DIR=$LIB_DIR/security
+	which systemctl 2>/dev/null
+	ISSYSTEMD="$?"
 
 	cd $INST_DIR
 }
